default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: student_dev

test:
  <<: *default
  database: student_test

production:
  <<: *default
  database: student_production
